In [4]:
import pandas as pd
from keras.models import Sequential
from keras.optimizers import Adam
from keras.losses import binary_crossentropy
from keras.layers import Dense
from keras.activations import sigmoid
from keras.utils import to_categorical
from sklearn.metrics import accuracy_score

/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
Using TensorFlow backend.
/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)

In [5]:
df=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data', header=None, index_col=0)

In [6]:
df.head()

         1   2   3   4   5   6   7   8   9   10
0
1000025   5   1   1   1   2   1   3   1   1   2
1002945   5   4   4   5   7  10   3   2   1   2
1015425   3   1   1   1   2   2   3   1   1   2
1016277   6   8   8   1   3   4   3   7   1   2
1017023   4   1   1   3   2   1   3   1   1   2

In [7]:
df[6].replace('?',None,inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 699 entries, 1000025 to 897471
Data columns (total 10 columns):
1     699 non-null int64
2     699 non-null int64
3     699 non-null int64
4     699 non-null int64
5     699 non-null int64
6     699 non-null object
7     699 non-null int64
8     699 non-null int64
9     699 non-null int64
10    699 non-null int64
dtypes: int64(9), object(1)
memory usage: 60.1+ KB

In [9]:
df[6]=df[6].astype('int')

In [10]:
df.describe()

,1,2,3,4,5,6,7,8,9,10
count,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000
mean,4.417740,3.134478,3.207439,2.806867,3.216023,3.529328,3.437768,2.866953,1.589413,2.689557
std,2.815741,3.051459,2.971913,2.855379,2.214300,3.635260,2.438364,3.053634,1.715078,0.951273
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000
25%,2.000000,1.000000,1.000000,1.000000,2.000000,1.000000,2.000000,1.000000,1.000000,2.000000
50%,4.000000,1.000000,1.000000,1.000000,2.000000,1.000000,3.000000,1.000000,1.000000,2.000000
75%,6.000000,5.000000,5.000000,4.000000,4.000000,6.000000,5.000000,4.000000,1.000000,4.000000
max,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,4.000000

In [11]:
df[10].replace(2,0,inplace=True)

In [12]:
df[10].replace(4,1,inplace=True)

In [13]:
df.describe()

,1,2,3,4,5,6,7,8,9,10
count,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000,699.000000
mean,4.417740,3.134478,3.207439,2.806867,3.216023,3.529328,3.437768,2.866953,1.589413,0.344778
std,2.815741,3.051459,2.971913,2.855379,2.214300,3.635260,2.438364,3.053634,1.715078,0.475636
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,2.000000,1.000000,1.000000,1.000000,2.000000,1.000000,2.000000,1.000000,1.000000,0.000000
50%,4.000000,1.000000,1.000000,1.000000,2.000000,1.000000,3.000000,1.000000,1.000000,0.000000
75%,6.000000,5.000000,5.000000,4.000000,4.000000,6.000000,5.000000,4.000000,1.000000,1.000000
max,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000

In [14]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1:]

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=1234)

In [17]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(559, 9)
(140, 9)
(559, 1)
(140, 1)

In [18]:
model=Sequential()
model.add(Dense(1, input_shape=(9,), activation='relu'))
model.add(Dense(2, activation='sigmoid'))
model.compile(Adam(lr=0.01), loss='binary_crossentropy')
history = model.fit(X_train, to_categorical(y_train), epochs=100)

Epoch 1/100
559/559 [==============================] - 0s 346us/step - loss: 0.7750
Epoch 2/100
559/559 [==============================] - 0s 38us/step - loss: 0.6725
Epoch 3/100
559/559 [==============================] - 0s 39us/step - loss: 0.6603
Epoch 4/100
559/559 [==============================] - 0s 40us/step - loss: 0.6532
Epoch 5/100
559/559 [==============================] - 0s 39us/step - loss: 0.6498
Epoch 6/100
559/559 [==============================] - 0s 39us/step - loss: 0.6477
Epoch 7/100
559/559 [==============================] - 0s 34us/step - loss: 0.6468
Epoch 8/100
559/559 [==============================] - 0s 36us/step - loss: 0.6460
Epoch 9/100
559/559 [==============================] - 0s 36us/step - loss: 0.6458
Epoch 10/100
559/559 [==============================] - 0s 32us/step - loss: 0.6457
Epoch 11/100
559/559 [==============================] - 0s 35us/step - loss: 0.6456
Epoch 12/100
559/559 [==============================] - 0s 34us/step - loss: 0.6455
Epoch 13/100
559/559 [==============================] - 0s 32us/step - loss: 0.6454
Epoch 14/100
559/559 [==============================] - 0s 37us/step - loss: 0.6454
Epoch 15/100
559/559 [==============================] - 0s 33us/step - loss: 0.6455
Epoch 16/100
559/559 [==============================] - 0s 32us/step - loss: 0.6454
Epoch 17/100
559/559 [==============================] - 0s 35us/step - loss: 0.6455
Epoch 18/100
559/559 [==============================] - 0s 36us/step - loss: 0.6456
Epoch 19/100
559/559 [==============================] - 0s 32us/step - loss: 0.6454
Epoch 20/100
559/559 [==============================] - 0s 36us/step - loss: 0.6455
Epoch 21/100
559/559 [==============================] - 0s 34us/step - loss: 0.6455
Epoch 22/100
559/559 [==============================] - 0s 32us/step - loss: 0.6455
Epoch 23/100
559/559 [==============================] - 0s 35us/step - loss: 0.6454
Epoch 24/100
559/559 [==============================] - 0s 36us/step - loss: 0.6456
Epoch 25/100
559/559 [==============================] - 0s 32us/step - loss: 0.6454
Epoch 26/100
559/559 [==============================] - 0s 36us/step - loss: 0.6457
Epoch 27/100
559/559 [==============================] - 0s 33us/step - loss: 0.6454
Epoch 28/100
559/559 [==============================] - 0s 31us/step - loss: 0.6454
Epoch 29/100
559/559 [==============================] - 0s 32us/step - loss: 0.6460
Epoch 30/100
559/559 [==============================] - 0s 34us/step - loss: 0.6455
Epoch 31/100
559/559 [==============================] - 0s 34us/step - loss: 0.6457
Epoch 32/100
559/559 [==============================] - 0s 35us/step - loss: 0.6454
Epoch 33/100
559/559 [==============================] - 0s 41us/step - loss: 0.6453
Epoch 34/100
559/559 [==============================] - 0s 40us/step - loss: 0.6456
Epoch 35/100
559/559 [==============================] - 0s 31us/step - loss: 0.6452
Epoch 36/100
559/559 [==============================] - 0s 32us/step - loss: 0.6453
Epoch 37/100
559/559 [==============================] - 0s 36us/step - loss: 0.6453
Epoch 38/100
559/559 [==============================] - 0s 31us/step - loss: 0.6454
Epoch 39/100
559/559 [==============================] - 0s 34us/step - loss: 0.6454
Epoch 40/100
559/559 [==============================] - 0s 31us/step - loss: 0.6454
Epoch 41/100
559/559 [==============================] - 0s 36us/step - loss: 0.6453
Epoch 42/100
559/559 [==============================] - 0s 34us/step - loss: 0.6458
Epoch 43/100
559/559 [==============================] - 0s 31us/step - loss: 0.6455
Epoch 44/100
559/559 [==============================] - 0s 36us/step - loss: 0.6453
Epoch 45/100
559/559 [==============================] - 0s 36us/step - loss: 0.6452
Epoch 46/100
559/559 [==============================] - 0s 31us/step - loss: 0.6453
Epoch 47/100
559/559 [==============================] - 0s 33us/step - loss: 0.6457
Epoch 48/100
559/559 [==============================] - 0s 38us/step - loss: 0.6452
Epoch 49/100
559/559 [==============================] - 0s 33us/step - loss: 0.6452
Epoch 50/100
559/559 [==============================] - 0s 31us/step - loss: 0.6455
Epoch 51/100
559/559 [==============================] - 0s 37us/step - loss: 0.6452
Epoch 52/100
559/559 [==============================] - 0s 33us/step - loss: 0.6453
Epoch 53/100
559/559 [==============================] - 0s 32us/step - loss: 0.6455
Epoch 54/100
559/559 [==============================] - 0s 33us/step - loss: 0.6451
Epoch 55/100
559/559 [==============================] - 0s 37us/step - loss: 0.6452
Epoch 56/100
559/559 [==============================] - 0s 31us/step - loss: 0.6454
Epoch 57/100
559/559 [==============================] - 0s 35us/step - loss: 0.6450
Epoch 58/100
559/559 [==============================] - 0s 38us/step - loss: 0.6452
Epoch 59/100
559/559 [==============================] - 0s 33us/step - loss: 0.6455
Epoch 60/100
559/559 [==============================] - 0s 33us/step - loss: 0.6452
Epoch 61/100
559/559 [==============================] - 0s 34us/step - loss: 0.6450
Epoch 62/100
559/559 [==============================] - 0s 35us/step - loss: 0.6450
Epoch 63/100
559/559 [==============================] - 0s 32us/step - loss: 0.6449
Epoch 64/100
559/559 [==============================] - 0s 34us/step - loss: 0.6450
Epoch 65/100
559/559 [==============================] - 0s 33us/step - loss: 0.6451
Epoch 66/100
559/559 [==============================] - 0s 36us/step - loss: 0.6453
Epoch 67/100
559/559 [==============================] - 0s 33us/step - loss: 0.6449
Epoch 68/100
559/559 [==============================] - 0s 35us/step - loss: 0.6454
Epoch 69/100
559/559 [==============================] - 0s 36us/step - loss: 0.6451
Epoch 70/100
559/559 [==============================] - 0s 35us/step - loss: 0.6450
Epoch 71/100
559/559 [==============================] - 0s 33us/step - loss: 0.6448
Epoch 72/100
559/559 [==============================] - 0s 36us/step - loss: 0.6448
Epoch 73/100
559/559 [==============================] - 0s 34us/step - loss: 0.6449
Epoch 74/100
559/559 [==============================] - 0s 31us/step - loss: 0.6448
Epoch 75/100
559/559 [==============================] - 0s 34us/step - loss: 0.6448
Epoch 76/100
559/559 [==============================] - 0s 36us/step - loss: 0.6447
Epoch 77/100
559/559 [==============================] - 0s 31us/step - loss: 0.6450
Epoch 78/100
559/559 [==============================] - 0s 35us/step - loss: 0.6447
Epoch 79/100
559/559 [==============================] - 0s 33us/step - loss: 0.6446
Epoch 80/100
559/559 [==============================] - 0s 32us/step - loss: 0.6448
Epoch 81/100
559/559 [==============================] - 0s 34us/step - loss: 0.6450
Epoch 82/100
559/559 [==============================] - 0s 35us/step - loss: 0.6446
Epoch 83/100
559/559 [==============================] - 0s 32us/step - loss: 0.6447
Epoch 84/100
559/559 [==============================] - 0s 37us/step - loss: 0.6451
Epoch 85/100
559/559 [==============================] - 0s 32us/step - loss: 0.6444
Epoch 86/100
559/559 [==============================] - 0s 33us/step - loss: 0.6445
Epoch 87/100
559/559 [==============================] - 0s 34us/step - loss: 0.6444
Epoch 88/100
559/559 [==============================] - 0s 35us/step - loss: 0.6445
Epoch 89/100
559/559 [==============================] - 0s 32us/step - loss: 0.6443
Epoch 90/100
559/559 [==============================] - 0s 34us/step - loss: 0.6447
Epoch 91/100
559/559 [==============================] - 0s 34us/step - loss: 0.6445
Epoch 92/100
559/559 [==============================] - 0s 31us/step - loss: 0.6441
Epoch 93/100
559/559 [==============================] - 0s 34us/step - loss: 0.6440
Epoch 94/100
559/559 [==============================] - 0s 34us/step - loss: 0.6436
Epoch 95/100
559/559 [==============================] - 0s 33us/step - loss: 0.6435
Epoch 96/100
559/559 [==============================] - 0s 37us/step - loss: 0.6431
Epoch 97/100
559/559 [==============================] - 0s 32us/step - loss: 0.6430
Epoch 98/100

559/559 [==============================] - 0s 33us/step - loss: 0.6429
Epoch 99/100
559/559 [==============================] - 0s 34us/step - loss: 0.6307
Epoch 100/100
559/559 [==============================] - 0s 34us/step - loss: 0.5214

In [19]:
y_pred=model.predict(X_test)

In [20]:
y_pred

array([[0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.00965258, 0.99850357],
       [0.11923248, 0.94922566],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.02522269, 0.9943843 ],
       [0.684924  , 0.30074072],
       [0.08987021, 0.96633095],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.30704588, 0.78871214],
       [0.169114  , 0.9148372 ],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.21355483, 0.8789456 ],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.5220918 , 0.5227603 ],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.658213  , 0.33644822],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.25767565, 0.83873725],
       [0.684924  , 0.30074072],
       [0.38169226, 0.7040467 ],
       [0.3751243 , 0.7118904 ],
       [0.5472431 , 0.48843265],
       [0.00104851, 0.9999274 ],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.3753634 , 0.71160614],
       [0.684924  , 0.30074072],
       [0.19648796, 0.8932925 ],
       [0.6176343 , 0.39167565],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.5068014 , 0.5434601 ],
       [0.684924  , 0.30074072],
       [0.5097359 , 0.53949934],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.09218088, 0.9650743 ],
       [0.684924  , 0.30074072],
       [0.01636404, 0.9969107 ],
       [0.55296195, 0.48059127],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.18322587, 0.90395933],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.21712339, 0.875859  ],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.00582871, 0.99924934],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.6706522 , 0.319739  ],
       [0.684924  , 0.30074072],
       [0.51182616, 0.53667456],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.344732  , 0.7472325 ],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.50321704, 0.54828966],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.6626621 , 0.33045724],
       [0.15286568, 0.92674565],
       [0.2802928 , 0.81645477],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.35290465, 0.7378876 ],
       [0.684924  , 0.30074072],
       [0.3552541 , 0.73517925],
       [0.684924  , 0.30074072],
       [0.5605392 , 0.47018722],
       [0.684924  , 0.30074072],
       [0.02094603, 0.99565744],
       [0.684924  , 0.30074072],
       [0.12385032, 0.9463172 ],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.07390156, 0.9745774 ],
       [0.684924  , 0.30074072],
       [0.5634032 , 0.46625116],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.01451337, 0.99738085],
       [0.05672562, 0.9825485 ],
       [0.684924  , 0.30074072],
       [0.52032846, 0.525155  ],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.67737734, 0.31076187],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.64640427, 0.3524208 ],
       [0.57650477, 0.44822836],
       [0.4227715 , 0.6534759 ],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.684924  , 0.30074072],
       [0.23224878, 0.86244893],
       [0.00333881, 0.99964887],
       [0.684924  , 0.30074072]], dtype=float32)

In [21]:
import numpy as np

In [22]:
y_pred_class=np.argmax(y_pred, axis=1)

In [23]:
y_pred_class

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0])

In [24]:
y_test['pred']=y_pred_class

/Users/akaghzi/Projects/Python/datascience/iba/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [36]:
y_test.head(50)

         10  pred
0
810104    0     0
869828    0     0
566346    0     0
1147044   0     0
1272039   0     0
1238021   0     0
1049837   0     0
897471    1     1
760001    1     1
324382    0     0
1287775   0     0
1330439   1     1
1313982   0     0
850831    1     1
1185610   0     0
1071084   0     0
822829    1     1
1192325   1     1
1196263   0     0
1115293   0     0
1204242   0     0
1117152   0     0
1174057   0     0
1225382   0     0
1198128   1     1
1201834   0     0
1277018   0     0
1227481   1     1
1239420   0     0
636437    0     0
1229929   0     0
1115282   1     0
730881    1     0
1199219   0     0
142932    1     1
1187457   0     0
320675    1     1
1230688   1     1
1257648   0     0
803531    1     1
733639    0     0
1173514   0     0
1182404   0     0
188336    1     1
1166654   1     0
1190386   1     1
1054593   1     0
1287282   0     0
1223306   0     0
1036172   0     0

In [26]:
print(f'Accuracy: {accuracy_score(y_test[10].values, y_test["pred"].values)}')

Accuracy: 0.8857142857142857

In [27]:
from sklearn.metrics import confusion_matrix

In [30]:
tn, fp, fn, tp = confusion_matrix(y_test[10].values, y_test["pred"].values).ravel()

In [31]:
print(f'tp: {tp}')
print(f'tn: {tn}')
print(f'fp: {fp}')
print(f'fn: {fn}')

tp: 34
tn: 90
fp: 3
fn: 13

In [32]:
34+90+3+13

140